### ISSUE TITLE
[Feature Request] upgrade to gymnasium 28.1

### ISSUE THREAD

**Issue by elliottower** [OmniSafeAI/safety-gymnasium#39]
### Required prerequisites

- [X] I have searched the [Issue Tracker](https://github.com/OmniSafeAI/safety-gymnasium/issues) and [Discussions](https://github.com/OmniSafeAI/safety-gymnasium/discussions) that this hasn't already been reported. (+1 or comment there if it has.)
- [ ] Consider asking first in a [Discussion](https://github.com/OmniSafeAI/safety-gymnasium/discussions/new).

### Motivation

Hi, I just wanted to make a quick issue to suggest upgrading to gymnasium 28.1. It shouldn’t require much if any code changes from 26.3 but there have been a number of bugs fixed since then. We have this repository listed under our third party environments list (https://gymnasium.farama.org/environments/third_party_environments/) and want to make sure they are as up to date as possible.

**Comment by XuehaiPan** [comment]
Hi @elliottower, thanks for raising this. We will migrate to the latest gymnasium this week. PRs are welcome.

**Comment by elliottower** [comment]
> Hi @elliottower, thanks for raising this. We will migrate to the latest gymnasium this week. PRs are welcome.

Sorry for not replying, glad to be of help bringing it to your attention, will update the third party environments list accordingly. Cheers.

**Comment by muchvo** [comment]
> > Hi @elliottower, thanks for raising this. We will migrate to the latest gymnasium this week. PRs are welcome.
> 
> Sorry for not replying, glad to be of help bringing it to your attention, will update the third party environments list accordingly. Cheers.

Thanks for helping us to be better. Cheers.
