### ISSUE TITLE
[BUG] python3.8/multiprocessing/connection.py EOFError

### ISSUE THREAD

**Issue by Zhaofeng-Tian** [OmniSafeAI/safety-gymnasium#40]
### Required prerequisites

- [X] I have read the documentation <https://safety-gymnasium.readthedocs.io>.
- [X] I have searched the [Issue Tracker](https://github.com/OmniSafeAI/safety-gymnasium/issues) and [Discussions](https://github.com/OmniSafeAI/safety-gymnasium/discussions) that this hasn't already been reported. (+1 or comment there if it has.)
- [ ] Consider asking first in a [Discussion](https://github.com/OmniSafeAI/safety-gymnasium/discussions/new).

### What version of Safety Gymnasium are you using?

0.2.0

### System information

>>> print(sys.version, sys.platform)
3.8.16 (default, Mar  2 2023, 03:21:46) 
[GCC 11.2.0] linux
>>> print(safety_gymnasium.__version__)
0.2.0

### Problem description

Runnning the first code in the document, tested in my ubuntu 16.04, 18.04, windows, met same problem in multiprocessing files.
File "/home/tian/anaconda3/envs/safe/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
  File "/home/tian/anaconda3/envs/safe/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
EOFError: 

### Reproducible example code

The Python snippets:

```python

```

Command lines:

```bash

```

Extra dependencies:

```text

```

Steps to reproduce:
# Runing the following codes, which is in the document.
import safety_gymnasium
env = safety_gymnasium.vector.make("SafetyCarGoal1-v0", render_mode="human", num_envs=8)
observation, info = env.reset(seed=0)
for _ in range(1000):
   action = env.action_space.sample()  # this is where you would insert your policy
   observation, reward, terminated, truncated, info = env.step(action)

   if terminated or truncated:
      observation, info = env.reset()
env.close()

### Traceback

```pytb
(safe) tian@ROG:~/safety-gymnasium$ python testrepo.py 
/home/tian/anaconda3/envs/safe/lib/python3.8/site-packages/glfw/__init__.py:916: GLFWError: (65543) b'GLX: Failed to create context: BadValue (integer parameter out of range for operation)'
  warnings.warn(message, GLFWError)
/home/tian/anaconda3/envs/safe/lib/python3.8/site-packages/glfw/__init__.py:916: GLFWError: (65543) b'GLX: Failed to create context: BadValue (integer parameter out of range for operation)'
  warnings.warn(message, GLFWError)
/home/tian/anaconda3/envs/safe/lib/python3.8/site-packages/glfw/__init__.py:916: GLFWError: (65543) b'GLX: Failed to create context: BadValue (integer parameter out of range for operation)'
  warnings.warn(message, GLFWError)
/home/tian/anaconda3/envs/safe/lib/python3.8/site-packages/glfw/__init__.py:916: GLFWError: (65543) b'GLX: Failed to create context: BadValue (integer parameter out of range for operation)'
  warnings.warn(message, GLFWError)
/home/tian/anaconda3/envs/safe/lib/python3.8/site-packages/glfw/__init__.py:916: GLFWError: (65538) b'Cannot set swap interval without a current OpenGL or OpenGL ES context'
  warnings.warn(message, GLFWError)
/home/tian/anaconda3/envs/safe/lib/python3.8/site-packages/glfw/__init__.py:916: GLFWError: (65538) b'Cannot set swap interval without a current OpenGL or OpenGL ES context'
  warnings.warn(message, GLFWError)
/home/tian/anaconda3/envs/safe/lib/python3.8/site-packages/glfw/__init__.py:916: GLFWError: (65538) b'Cannot set swap interval without a current OpenGL or OpenGL ES context'
  warnings.warn(message, GLFWError)
/home/tian/anaconda3/envs/safe/lib/python3.8/site-packages/glfw/__init__.py:916: GLFWError: (65538) b'Cannot set swap interval without a current OpenGL or OpenGL ES context'
  warnings.warn(message, GLFWError)
python: /builds/florianrhiem/pyGLFW/glfw-3.3.8/src/window.c:646: glfwGetFramebufferSize: Assertion `window != ((void *)0)' failed.
python: /builds/florianrhiem/pyGLFW/glfw-3.3.8/src/window.c:646: glfwGetFramebufferSize: Assertion `window != ((void *)0)' failed.
python: /builds/florianrhiem/pyGLFW/glfw-3.3.8/src/window.c:646: glfwGetFramebufferSize: Assertion `window != ((void *)0)' failed.
python: /builds/florianrhiem/pyGLFW/glfw-3.3.8/src/window.c:646: glfwGetFramebufferSize: Assertion `window != ((void *)0)' failed.
/home/tian/anaconda3/envs/safe/lib/python3.8/site-packages/glfw/__init__.py:916: GLFWError: (65543) b'GLX: Failed to create context: BadValue (integer parameter out of range for operation)'
  warnings.warn(message, GLFWError)
/home/tian/anaconda3/envs/safe/lib/python3.8/site-packages/glfw/__init__.py:916: GLFWError: (65543) b'GLX: Failed to create context: BadValue (integer parameter out of range for operation)'
  warnings.warn(message, GLFWError)
/home/tian/anaconda3/envs/safe/lib/python3.8/site-packages/glfw/__init__.py:916: GLFWError: (65538) b'Cannot set swap interval without a current OpenGL or OpenGL ES context'
  warnings.warn(message, GLFWError)
python: /builds/florianrhiem/pyGLFW/glfw-3.3.8/src/window.c:646: glfwGetFramebufferSize: Assertion `window != ((void *)0)' failed.
/home/tian/anaconda3/envs/safe/lib/python3.8/site-packages/glfw/__init__.py:916: GLFWError: (65538) b'Cannot set swap interval without a current OpenGL or OpenGL ES context'
  warnings.warn(message, GLFWError)
python: /builds/florianrhiem/pyGLFW/glfw-3.3.8/src/window.c:646: glfwGetFramebufferSize: Assertion `window != ((void *)0)' failed.
/home/tian/anaconda3/envs/safe/lib/python3.8/site-packages/glfw/__init__.py:916: GLFWError: (65543) b'GLX: Failed to create context: BadValue (integer parameter out of range for operation)'
  warnings.warn(message, GLFWError)
/home/tian/anaconda3/envs/safe/lib/python3.8/site-packages/glfw/__init__.py:916: GLFWError: (65543) b'GLX: Failed to create context: BadValue (integer parameter out of range for operation)'
  warnings.warn(message, GLFWError)
/home/tian/anaconda3/envs/safe/lib/python3.8/site-packages/glfw/__init__.py:916: GLFWError: (65538) b'Cannot set swap interval without a current OpenGL or OpenGL ES context'
  warnings.warn(message, GLFWError)
python: /builds/florianrhiem/pyGLFW/glfw-3.3.8/src/window.c:646: glfwGetFramebufferSize: Assertion `window != ((void *)0)' failed.
/home/tian/anaconda3/envs/safe/lib/python3.8/site-packages/glfw/__init__.py:916: GLFWError: (65538) b'Cannot set swap interval without a current OpenGL or OpenGL ES context'
  warnings.warn(message, GLFWError)
python: /builds/florianrhiem/pyGLFW/glfw-3.3.8/src/window.c:646: glfwGetFramebufferSize: Assertion `window != ((void *)0)' failed.
Traceback (most recent call last):
  File "testrepo.py", line 6, in <module>
    observation, reward, terminated, truncated, info = env.step(action)
  File "/home/tian/anaconda3/envs/safe/lib/python3.8/site-packages/gymnasium/vector/vector_env.py", line 197, in step
    return self.step_wait()
  File "/home/tian/safety-gymnasium/safety_gymnasium/vector/async_vector_env.py", line 122, in step_wait
    result, success = pipe.recv()
  File "/home/tian/anaconda3/envs/safe/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/home/tian/anaconda3/envs/safe/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/home/tian/anaconda3/envs/safe/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
/home/tian/anaconda3/envs/safe/lib/python3.8/site-packages/gymnasium/vector/async_vector_env.py:457: UserWarning: WARN: Calling `close` while waiting for a pending call to `step` to complete.
Exception ignored in: <function AsyncVectorEnv.__del__ at 0x7f11c2ebd430>
Traceback (most recent call last):
  File "/home/tian/anaconda3/envs/safe/lib/python3.8/site-packages/gymnasium/vector/async_vector_env.py", line 546, in __del__
  File "/home/tian/anaconda3/envs/safe/lib/python3.8/site-packages/gymnasium/vector/vector_env.py", line 265, in close
  File "/home/tian/anaconda3/envs/safe/lib/python3.8/site-packages/gymnasium/vector/async_vector_env.py", line 461, in close_extras
  File "/home/tian/safety-gymnasium/safety_gymnasium/vector/async_vector_env.py", line 122, in step_wait
  File "/home/tian/anaconda3/envs/safe/lib/python3.8/multiprocessing/connection.py", line 250, in recv
  File "/home/tian/anaconda3/envs/safe/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
  File "/home/tian/anaconda3/envs/safe/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
EOFError:
```

**Comment by Zhaofeng-Tian** [comment]
I ran the code on my three devices, and they all failed.

**Comment by muchvo** [comment]
Hi, @Zhaofeng-Tian you choose 'human' render_mode when rendering 8 environment instances at the same time, it requires too many resources beyond your computers and the power of your hardware. To verify this, you can try to set `num_envs=2`, it works on my laptop. If you don't need to train a policy and continuously render it, you can set the `render_mode="rgb_array"` and call `env.render()` manually when needed.
If it helps, please let me know.

**Comment by Zhaofeng-Tian** [comment]
Hi there,

thank you for your fast response. I will check it out when I go to the lab
today.
But it seems my Windows still doesn't work with your suggestions when I run
the same code. It is still about the multiprocessing system,
the error traceback was recorded below.
By the way, I was wondering if multiprocessing really helps, and how many
seeds usually can be run at the same time in a normal machine, e.g., a
single 2080 card machine?

Thank you, I appreciate your work.
Zhaofeng


(safe)
C:\Users\61602\Desktop\Coding\safety-gymnasium>C:/App/Anaconda/envs/safe/python.exe
c:/Users/61602/Desktop/Coding/test.py
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\App\Anaconda\envs\safe\lib\multiprocessing\spawn.py", line 116,
in spawn_main
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\App\Anaconda\envs\safe\lib\multiprocessing\spawn.py", line 116,
in spawn_main
    exitcode = _main(fd, parent_sentinel)
    exitcode = _main(fd, parent_sentinel)
  File "C:\App\Anaconda\envs\safe\lib\multiprocessing\spawn.py", line 125,
in _main
  File "C:\App\Anaconda\envs\safe\lib\multiprocessing\spawn.py", line 125,
in _main
    prepare(preparation_data)
    prepare(preparation_data)
  File "C:\App\Anaconda\envs\safe\lib\multiprocessing\spawn.py", line 236,
in prepare
  File "C:\App\Anaconda\envs\safe\lib\multiprocessing\spawn.py", line 236,
in prepare
    _fixup_main_from_path(data['init_main_from_path'])
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\App\Anaconda\envs\safe\lib\multiprocessing\spawn.py", line 287,
in _fixup_main_from_path
  File "C:\App\Anaconda\envs\safe\lib\multiprocessing\spawn.py", line 287,
in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "C:\App\Anaconda\envs\safe\lib\runpy.py", line 265, in run_path
    main_content = runpy.run_path(main_path,
  File "C:\App\Anaconda\envs\safe\lib\runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
    return _run_module_code(code, init_globals, run_name,
  File "C:\App\Anaconda\envs\safe\lib\runpy.py", line 97, in
_run_module_code
  File "C:\App\Anaconda\envs\safe\lib\runpy.py", line 97, in
_run_module_code
    _run_code(code, mod_globals, init_globals,
    _run_code(code, mod_globals, init_globals,
  File "C:\App\Anaconda\envs\safe\lib\runpy.py", line 87, in _run_code
  File "C:\App\Anaconda\envs\safe\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
    exec(code, run_globals)
  File "c:\Users\61602\Desktop\Coding\test.py", line 2, in <module>
  File "c:\Users\61602\Desktop\Coding\test.py", line 2, in <module>
    env = safety_gymnasium.vector.make("SafetyCarGoal1-v0",
render_mode="human", num_envs=2)
    env = safety_gymnasium.vector.make("SafetyCarGoal1-v0",
render_mode="human", num_envs=2)
  File
"C:\Users\61602\Desktop\Coding\safety-gymnasium\safety_gymnasium\vector\__init__.py",
line 90, in make
  File
"C:\Users\61602\Desktop\Coding\safety-gymnasium\safety_gymnasium\vector\__init__.py",
line 90, in make
    return SafetyAsyncVectorEnv(env_fns) if asynchronous else
SafetySyncVectorEnv(env_fns)
  File
"C:\Users\61602\Desktop\Coding\safety-gymnasium\safety_gymnasium\vector\async_vector_env.py",
line 66, in __init__
    return SafetyAsyncVectorEnv(env_fns) if asynchronous else
SafetySyncVectorEnv(env_fns)
  File
"C:\Users\61602\Desktop\Coding\safety-gymnasium\safety_gymnasium\vector\async_vector_env.py",
line 66, in __init__
    super().__init__(
  File
"C:\App\Anaconda\envs\safe\lib\site-packages\gymnasium\vector\async_vector_env.py",
line 164, in __init__
    super().__init__(
  File
"C:\App\Anaconda\envs\safe\lib\site-packages\gymnasium\vector\async_vector_env.py",
line 164, in __init__
    process.start()
  File "C:\App\Anaconda\envs\safe\lib\multiprocessing\process.py", line
121, in start
    process.start()
  File "C:\App\Anaconda\envs\safe\lib\multiprocessing\process.py", line
121, in start
    self._popen = self._Popen(self)
    self._popen = self._Popen(self)
  File "C:\App\Anaconda\envs\safe\lib\multiprocessing\context.py", line
327, in _Popen
  File "C:\App\Anaconda\envs\safe\lib\multiprocessing\context.py", line
327, in _Popen
    return Popen(process_obj)
    return Popen(process_obj)
  File
"C:\App\Anaconda\envs\safe\lib\multiprocessing\popen_spawn_win32.py", line
45, in __init__
  File
"C:\App\Anaconda\envs\safe\lib\multiprocessing\popen_spawn_win32.py", line
45, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\App\Anaconda\envs\safe\lib\multiprocessing\spawn.py", line 154,
in get_preparation_data
  File "C:\App\Anaconda\envs\safe\lib\multiprocessing\spawn.py", line 154,
in get_preparation_data
    _check_not_importing_main()
  File "C:\App\Anaconda\envs\safe\lib\multiprocessing\spawn.py", line 134,
in _check_not_importing_main
    _check_not_importing_main()
  File "C:\App\Anaconda\envs\safe\lib\multiprocessing\spawn.py", line 134,
in _check_not_importing_main
    raise RuntimeError('''
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.    raise
RuntimeError('''

RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

muchvo ***@***.***> 于2023年4月11日周二 06:31写道：

**Comment by muchvo** [comment]
Thanks for your feedback. 
I have reproduced it on my Windows laptop, our library has not officially support Windows for now, but it is on our to-do list already, we will fix this bug before we provide official support for Windows. You can run this library on Linux for now.
The multiprocessing actually helps, environments in Safety-Gymnasium are more complex than mujoco environments in Gymnasium, so we need multiprocessing to boost our speed of collecting data, we implement it on [OmniSafe](https://github.com/OmniSafeAI/omnisafe/blob/main/examples/train_from_custom_dict.py#L24), you can compare the speed based on OmniSafe. 
And because our library is based on mujoco which completes all calculations on the CPU, the capability of CPU and memory decides the number of environments that can be run at the same time whether you use CUDA to calculate gradients or not. Last point, the number of multiprocessing will affect the performance of algorithms, refer to [it](https://iclr-blog-track.github.io/2022/03/25/ppo-implementation-details/).

**Comment by Zhaofeng-Tian** [comment]
Thank you for your explanations. I got the lib just now, I changed env_num
to 1, both my ubuntu 16.04 and 18.04 reported same original bugs that I
reported on Github.
Then I changed the render_mode to "rgb_array", it reported a new bug shown
below:

(saferl) ***@***.***:~/safety-gymnasium$ python test.py
Traceback (most recent call last):
  File "test.py", line 6, in <module>
    observation, reward, terminated, truncated, info = env.step(action)
ValueError: too many values to unpack (expected 5)

muchvo ***@***.***> 于2023年4月11日周二 09:48写道：

**Comment by Zhaofeng-Tian** [comment]
Hi there,

As my last email said, there were still bugs on my both ubuntu machines. I
was wondering if any content in your document is outdated right now?
Please let me know if there is anyway to fix this issue. Thank you very
much!

Best regards,
Zhaofeng

muchvo ***@***.***> 于2023年4月11日周二 09:48写道：

**Comment by muchvo** [comment]
> Thank you for your explanations. I got the lib just now, I changed env_num to 1, both my ubuntu 16.04 and 18.04 reported same original bugs that I reported on Github. Then I changed the render_mode to "rgb_array", it reported a new bug shown below: (saferl) ***@***.***:~/safety-gymnasium$ python test.py Traceback (most recent call last): File "test.py", line 6, in <module> observation, reward, terminated, truncated, info = env.step(action) ValueError: too many values to unpack (expected 5) muchvo 


Please change `observation, reward, terminated, truncated, info = env.step(action)` to `observation, reward, cost, terminated, truncated, info = env.step(action)`
For examples, you can check out our official examples in [examples](https://github.com/OmniSafeAI/safety-gymnasium/tree/main/examples)

**Comment by muchvo** [comment]
> 

Hello, Zhaofeng. Did you try to run our code in examples? And is your machine headless?

**Comment by muchvo** [comment]
If you have more questions, feel free to reopen it.

**Comment by Zhaofeng-Tian** [comment]
Hi there,

Sorry for my late response, I was out of the project for a while. I tried
today, the example successfully ran on my Ubuntu16.04 machine.
Thank you again for your time,

Zhaofeng

muchvo ***@***.***> 于2023年4月13日周四 11:38写道：

**Comment by zmsn-2077** [comment]
Congratulations on solving the problem. If this repository has been helpful to you, you can give a `star` to the repository, thus inspiring us to do more for the community. We also hope you can recommend this repository to your friends who are doing research on safe reinforcement learning. We will actively provide detailed technical support.
QAQ.

**Comment by zmsn-2077** [comment]
Yes, I am the co-author of CUP.

**Comment by Zhaofeng-Tian** [comment]
That is a solid work, I am reading it right now. Will follow up your future
work as well. 👍👍👍

Jiaming Ji ***@***.***> 于2023年4月27日周四 11:30写道：

**Comment by Zhaofeng-Tian** [comment]
Great! Talk to you later.

Best,
Zhaofeng

Jiaming Ji ***@***.***> 于2023年4月27日周四 11:42写道：
