### ISSUE TITLE
[Question] Any benchmark results available for the set of tasks?

### ISSUE THREAD

**Issue by liuzuxin** [OmniSafeAI/safety-gymnasium#42]
### Required prerequisites

- [X] I have read the documentation <https://safety-gymnasium.readthedocs.io>.
- [X] I have searched the [Issue Tracker](https://github.com/OmniSafeAI/safety-gymnasium/issues) and [Discussions](https://github.com/OmniSafeAI/safety-gymnasium/discussions) that this hasn't already been reported. (+1 or comment there if it has.)
- [X] Consider asking first in a [Discussion](https://github.com/OmniSafeAI/safety-gymnasium/discussions/new).

### Questions

Hi authors, thanks for the great work. I am planning to use this repo as one of my testing playgrounds. I am wondering if there are training results for the `Goal, Button, Push` tasks available, since I found that using my PPO-Lag algorithm with a cost-limit 20 on these tasks will result in very low rewards (~6 for PointGoal1). Therefore, some benchmark results can help me to understand whether my obtained reward/cost ranges are normal for these tasks. Thanks!

**Comment by muchvo** [comment]
Hi, zuxin, thanks for your feedback. For our environments, We have systematically tested them, and the benchmark results will be released in the next seven days. And for the v0 series task in Safe Navigation, we completely implemented them as Safety-Gym setting, so the normal performance is corresponding to it. 
Here is several algorithms' performance that is averaged on five seeds.
`SafetyPointGoal1-v0`
![image](https://user-images.githubusercontent.com/118189931/231946877-9ca46ec0-5de6-4eb6-9a6e-a47d2857a3c1.png)
`SafetyCarGoal1-v0`
![image](https://user-images.githubusercontent.com/118189931/231947030-4aa37141-9a2e-4881-8603-c8c042969bcf.png)

**Comment by muchvo** [comment]
And we have implemented a new series of tasks called Safe Velocity. The constraint is added on the real-time velocity of the agent. If the agent's speed is beyond a threshold, it will receive a cost. Here is one example for `SafetyHopperVelocity-v1`:
![image](https://user-images.githubusercontent.com/118189931/231975688-e1c05809-e2cf-4a49-9dff-04e39f0c9c2a.png)
`PPO`

https://user-images.githubusercontent.com/118189931/231975824-faf9f54a-9ccb-4e05-9907-2fe32daa78ab.mp4

`PPOLag`

https://user-images.githubusercontent.com/118189931/231976028-23c03260-3c37-42b1-9301-1447fd3e4995.mp4
