### ISSUE TITLE
[Feature Request] Adding support for standard gymnasium API by removing the `cost` from the return variables

### ISSUE THREAD

**Issue by liuzuxin** [OmniSafeAI/safety-gymnasium#43]
### Required prerequisites

- [X] I have searched the [Issue Tracker](https://github.com/OmniSafeAI/safety-gymnasium/issues) and [Discussions](https://github.com/OmniSafeAI/safety-gymnasium/discussions) that this hasn't already been reported. (+1 or comment there if it has.)
- [ ] Consider asking first in a [Discussion](https://github.com/OmniSafeAI/safety-gymnasium/discussions/new).

### Motivation

Hi all, I have been using this repo for a while and really appreciate your efforts in organizing all the tasks, which will for sure benefit the entire safe RL community. However, I am a bit confused regarding the design of explicitly returning the cost value when executing the `step()` function, i.e.:
 
```python
obs, reward, cost, terminated, truncated, info = env.step(act)
```

I am curious that what's the particular motivation for modifying the original gymnasium API, since I personally think sticking to the standard one, i.e.,

```python
obs, reward, terminated, truncated, info = env.step(act)
```

where "cost" is in the info dict`, would be better and more convenient for usage. My thoughts are as follows:

1. Using the standard API can help us to better integrate with popular RL libraries, such as tianshou and stable-baselines3, without modifying too much about their data collection part. I noticed that the `level-0` tasks are mostly constraint-free, so using the standard API can help us to test the basic environment more conveniently with other non-safe RL libraries. I personally have had this issue since modifying the [collector in tianshou](https://github.com/thu-ml/tianshou/blob/master/tianshou/data/collector.py) is not a trivial thing and might not be elegant. 
2. I think the current API only supports a single constraint setting, which might not be easily extended to multiple constraints. For example, if there are two constraints and we need to consider their costs separately, then the current `cost` returning variable seems to be in an awkward position. In contrast, adding more entries/keys in the `info` dict will be much more extendable as well as making the API clean and consistent. I do believe that extending the set of environments to multiple-constraint settings in the future would be interesting and promising.
3. We may not be able to apply standard gymnasium wrappers easily due to the API changes.
4. Converting the current API to the standard gymnasium with a wrapper may not be very elegant in terms of implementation.

I tried to use this repo as a standard gymnasium way by using the following code snippet, but it failed:

```python
import gymnasium as gym
import safety_gymnasium

env = gym.make("SafetyCarCircle1-v0")
env.reset()
env.step(env.action_space.sample())
```

If I want to convert it to standard gymnasium API, I have to do the following:

```python
import gymnasium as gym
import safety_gymnasium as sgym

class SafetyGymnasiumWrapper(gym.Wrapper):
    def __init__(self, env: gym.Env):
        super().__init__(env)
    def step(self, action):
        obs, reward, cost, terminated, truncated, info = super().step(action)
        return obs, reward, terminated, truncated, info

env = SafetyGymnasiumWrapper(sgym.make("SafetyCarCircle1-v0"))
env.reset()
print(env.step(env.action_space.sample()))
```

### Solution

I am wondering if the authors could provide an argument when creating the environment, such that we can easily switch between the proposed step API and the standard gymnasium API. For example, the ideal usage could be something like:

```python
import gymnasium as gym
import safety_gymnasium as sgym

# use standard gymnasium API
env = gym.make("SafetyCarCircle1-v0", standard_api=True)
env.reset()
obs, reward, terminated, truncated, info = env.step(env.action_space.sample())

# use the current safety-gymnasium API
env = sgym.make("SafetyCarCircle1-v0", standard_api=False)
env.reset()
obs, reward, cost, terminated, truncated, info = env.step(env.action_space.sample())
```

Ideally, the default value for the `standard_api` argument should be `True` to stick with the standard gymnasium style usage.

I am looking forward to hearing from the authors regarding your thoughts on this problem. Thanks.

### Additional context

By the way, it seems that the [discussion](https://github.com/OmniSafeAI/safety-gymnasium/discussions/new) tab is not open. It is always 404 on my end.

**Comment by XuehaiPan** [comment]
Hi @liuzuxin, thanks for the insightful feedback and detailed comment.

Is the wrapper in your comment resolve your concern? For clarity, it is:

```python
import gymnasium as gym
import safety_gymnasium as sgym

class SafetyGymnasium2Gymnasium(gym.Wrapper):
    def step(self, action):
        obs, reward, cost, terminated, truncated, info = super().step(action)
        info['cost'] = cost
        return obs, reward, terminated, truncated, info

env = SafetyGymnasium2Gymnasium(sgym.make("SafetyCarCircle1-v0"))
```

------

Here are my answers to your concerns about the API design. We are open to discussion if you disagree.

> 1. Using the standard API can help us to better integrate with popular RL libraries, such as tianshou and stable-baselines3, without modifying too much about their data collection part.

The existing RL libraries are not designed for Safe RL algorithms. I'm not surprised that they are not out-of-box support safety-gymnasium. Since most RL libraries require users to provide a function `make_env` to create environments. There is not much extra work to convert a safety-gymnasium environment to a gymnasium environment using the wrapper above.

```python
def make_env(*args, **kwargs):
    safe_env = safety_gymnasium.make("SafetyCarCircle1-v0")
    env = SafetyGymnasium2Gymnasium(safe_env)
    env = GymnasiumWrapper1(env)
    ...
    env = GymnasiumWrapperN(env)
    return env

some_library.train(env=make_env, algo='PPO', ...)
```

You can also register the converted environment to `gymnasium.make`:

```python
def make_gymnasium_env(*args, **kwargs):
    safe_env = safety_gymnasium.make("SafetyCarCircle1-v0")
    env = SafetyGymnasium2Gymnasium(safe_env)
    return env

gymnasium.register(id="SafetyCarCircle1GymnasiumAPI-v0", entry_point=make_gymnasium_env)

env = gymnasium.make("SafetyCarCircle1GymnasiumAPI-v0")  # follows standard gymnasium API
```

------

> 2. I think the current API only supports a single constraint setting, which might not be easily extended to multiple constraints.

We do support multi-constraint settings. The `cost` variable can be a `list` or `numpy.ndarray`. Also, I don't think putting `cost` in the `info` dict is better.

1. Having a separate `cost` variable makes batch preprocessing much easier. We can do:

    ```python
    cost_buffer = [cost1, cost2, ..., costN]  # cost may be a ndarray
    cost_tensor = torch.from_numpy(np.asarray(cost_buffer))
    ```

    and

    ```python
    transactions = [
        (obs1, act1, next_obs1, reword1, cost1, term1, trunc1, info1),
        (obs2, act2, next_obs2, reword2, cost2, term2, trunc2, info2),
        ...
    ]

    obs, act, next_obs, reword, cost, term, trunc, info = zip(*transactions)
    ```

    If you put `cost` in the `info` dict, you need to fetch the cost values from `dict`s first then do batch stacking.

2. Having a separate `cost` variable enforces an API design. This makes users customize their environment for safety RL in a standard way. This holds a similar argument as Gymnasium decide to extract `TimeLimit.truncated` from `info` into a separate `truncated` field.

    1. The `cost` can be missing: If the custom environment's `step` function misses the `cost` field, the algorithm could fail early and warn the user to revisit their environment design. However, if we put `cost` in the `info` dict, the RL algorithm may not fail but produce poor performance results.

    2. It's hard to design keys for multi-constraint settings: We think the Python `dict` is too flexible. You can have arbitrary hashable objects as keys in the `dict`s. I haven't found an elegant way to support multi-constraint settings with dict approach. I don't think `'cost'`, `'cost1'`, `'cost2'` resolves the concern. Also, users may miss some keys or have extra keys in the `info` dict.

    3. It's much easier to extend our API to multi-agent settings.

    4. Initial step handling: In the new gymnasium API, `env.reset()` also returns an `info` dict. This makes API design much harder:

    ```python
    class MyEnv(safety_gymnasium.Env):
          def get_info(self):
              ...

          def get_obs(self):
              ...

          def reset(self, **kwargs):
              return self.get_obs(), self.get_info()

          def step(self, action):
              ...

              return self.get_obs(), ..., self.get_info()
    ```

------

> 3. We may not be able to apply standard gymnasium wrappers easily due to the API changes.

This would be a limitation of our API design. We would investigate this. Here is a temporary walkaround:

```python
class GymnasiumWrapperStack(gym.Wrapper):
    def __init__(self, safe_env: safety_gymnasium.Env, wrappers: list[gym.Wrapper]):
        self.safe_env = safe_env
        env = SafetyGymnasium2Gymnasium(safe_env)comments
        for wrapper in wrappers:
            env = wrapper(env)
        super().__init__(env)

    def step(self, action):
        observation, reward, terminated, truncated, info = super().step(action)
        cost = info.pop('cost')
        return observation, reward, cost, terminated, truncated, info

env = GymnasiumWrapperStack(
    safe_env=safety_gymnasium.make("SafetyCarCircle1-v0"),
    wrappers=[  # gymnasium wrappers
        NormalizeObservation,
        NormalizeAction,
        StackFrame,
        functools.partial(SomeWrapper, kwarg1=..., kwarg2=..., ...),
        ...
    ],
)
```

------

> 4. Converting the current API to the standard gymnasium with a wrapper may not be very elegant in terms of implementation.

I think using wrappers is the common solution in the RL community. And it's more flexible. Also, see my comments above.

------

> 0. Ideally, the default value for the `standard_api` argument should be True to stick awith the standard gymnasium style usage.

This is a breaking change and not backward compatible.

------

> By the way, it seems that the discussion tab is not open. It is always 404 on my end.

Thanks for the feedback. We opened the discussion page.

**Comment by liuzuxin** [comment]
Hi @XuehaiPan , thank you for your detailed and prompt response. Your explanations make a lot of sense and I appreciate your insights.

I brought up this discussion because I have noticed that many publicly available implementations of safe RL algorithms, including my own packages, and safe RL environments, such as [MetaDrive](https://metadrive-simulator.readthedocs.io/en/latest/reward_cost_and_termination_function.html) and Bullet-safety-gym still use the original API design, with the exception of your omnisafe repository (which I believe is also an excellent project). Therefore, I was trying to think of a way to use `safety_gymnasium` without deviating too much from other repositories, for example, using the same training script for both the `metadrive` env and the `safety_gymnasium` env with a consistent API.

I think the `make_env` solution you provided is a great idea. In addition, I believe that providing workflows for both converting `safety_gymnasium` to the `gymnasium` API and converting other `gymnasium` environments to the `safety_gymnasium` API could be very helpful. Would you consider adding these instructions to the documentation?

**Comment by XuehaiPan** [comment]
> I think the `make_env` solution you provided is a great idea. In addition, I believe that providing workflows for both converting `safety_gymnasium` to the `gymnasium` API and converting other `gymnasium` environments to the `safety_gymnasium` API could be very helpful. Would you consider adding these instructions to the documentation?

I think out-of-box provide wrappers like `SafetyGymnasium2Gymnasium`, `Gymnasium2SafetyGymnasium` would be great. We would review a PR for this.
